services:
 nginx:
  container_name: nginx
  image: nginx
  ports:
  - "8080:80"
  - "9090:9090"
  volumes:
  - ./nginx-data/site-data:/var/www/
  - ./nginx-data/sites-available:/etc/nginx/sites-available
  - ./nginx-data/conf/nginx.conf:/etc/nginx/nginx.conf
